### ISSUE TITLE
Use IoC libraries in CHe

### ISSUE THREAD

**Issue by amedranogil** [universAAL/context#3]
If CHe uses [Inversion of Control libraries](https://github.com/universAAL/utilities/tree/master/utilities.ioc) then it will be assured the operations involing the serializer will never throw a NPE.

These libraries where developed for the MTGW, & I find them extremely useful in my developments. Maybe they should be part of middleware utils & not an extra util library.

**Comment by amedranogil** [comment]
same for Prof.server.

I am getting a lot of errors in my ITests because of NPE because of not correctly configured parser in both modules. IoC will pause the execution until the parser is correctly configured, which will avoid having to set an arbritary timer before each IT.

**Comment by Alfiva** [comment]
Great, but I have no idea how to use them.
+info

**Comment by amedranogil** [comment]
`DependencyProxy<MessageContentSerializer> serializer;
serializer = new PassiveDependencyProxy<MessageContentSerializer>(
				context,
				new Object[] { MessageContentSerializer.class.getName() });
serializer.getObject().serialize(r);`

The getObject will try fetch the object automatically (removing the need for OSGi service subscription) and in the case of PassiveDependencyProxy it will suspend execution until the module is registered.

**Comment by amedranogil** [comment]
I would vote for the inclusion of `org.universAAL.ioc.dependencies` full package (including the implementations) in mw.container.xfaces.core module.
other options are:
- new middleware module
- inclusion through utils (this will require some rework of the POM and features so that utils are included right after MW). This was my initial idea, since these libraries are Java5.

**Comment by cstockloew** [comment]
This is closely related to [this discussion](http://forge.universaal.org/gf/project/middleware/forum/?_forum_action=ForumMessageBrowse&thread_id=164&action=ForumBrowse&forum_id=150) in forge.

* I would use the naming we already have, i.e.  use SharedObject instead of dependency (from the naming I first thought ioc was about maven dependencies ;-) ).
* Java 5 is no problem anymore
* I don't really see the need for 3 classes (and an interface). I think it can be easily done in 1 class with methods like getObject(), waitForObject(), and waitForObject(long timeout). Am I missing something?
* release (or stop or ungetService) is missing

**Comment by amedranogil** [comment]
This library internally uses the SharedObject concept, they just implement 3 different ways to address the issue of fetching the object, the first is the passive way (ie: wait for ever until the object is available), another way is to wait until there is a timeout or just give a null pointer exception (when you wanna see if the object is there or not).
I think I will go with the util option, which means I will have to do some work with the POMs and features so that utils can be loaded and runned from the other EG (which i guess is great news for @Alfiva )

**Comment by cstockloew** [comment]
I would prefer to have at least something directly in container module as it is also needed for some parts of the mw. You used it in config manager and I wanted to use it in control bus. More modules can be adapted after it's finished. Maybe I can prepare a concrete proposal.

What do you say about the other two modifications?

**Comment by amedranogil** [comment]
Yesterday I finished setting up the framework to import utils in all projects beyond ontologies; as well as embedding the usage of the library in the CHe, prof.server, MTGW, and the 4 new security modules. So I went with the 3rd option I proposed.
I guess we could still put it in the MW. But There was 1 issue: because of an internal check in one of the implementations which uses java reflection, there was the need to set up a DynamicImport in the bundle. This check stems from a [comment in the code](https://github.com/universAAL/utilities/blob/master/utilities.ioc/src/main/java/org/universAAL/ioc/dependencies/impl/PassiveDependencyProxy.java#L105) that states the MW notifies all sharedObjectListeners for all sharedObjects and not just the presented filters (@kismet or I wrote this comment when developing the MTGW, long time ago, IDK if this issue is resolved or not, but I trust at the time this was the case).

@cstockloew I did not understand your comment: what is that I used in the config Manager? which two modifications are you referring to (maybe I need to clarify my comment, I just added an EDIT)?

**Comment by amedranogil** [comment]
BTW this issue is resolved in pull request #4

**Comment by cstockloew** [comment]
Your comment in the code (about sharedObjectListeners) and my work on buses and integration of the DistributedMWManager have originally triggered the discussion in forge. When I wanted to fix the issue I saw the need for a "slightly" bigger change and it was easier to do the change all in one than to first fix the issue for sharedObjectListeners.

For your other questions, please have a look at the link I provided ([the discussion in forge](http://forge.universaal.org/gf/project/middleware/forum/?_forum_action=ForumMessageBrowse&thread_id=164&action=ForumBrowse&forum_id=150)):
* MOD1: removing xfaces
* MOD2: introducing SharedObjectParams
* MOD3: introducing helper classes (like SharedObjectConnector from config manager)

**Comment by amedranogil** [comment]
Sorry, didn't look into the forge discussion.
- MOD1: ok, but be careful with Maven POM updates! those need to be done almost everywhere (not really sure though)
- MOD2: ok. but this might also mean a change on the level of an API update, there are many components  that rely on shared objects, specially the serializer.
- MOD3: ok, although  SharedObjectConnector is a fixed class only for 3 managers, where the IoC libraries do the same with whichever SharedObject you need (plus it has the three different behaviours, also extensions to these behaviours are possible).

**Comment by amedranogil** [comment]
This discussion is steering away from the original issue, maybe we should open a new issue, probably in Middleware.

I have still to do the importing of issues from gforge...
