### ISSUE TITLE
Profiling server services allways return Callstatus suceeded

### ISSUE THREAD

**Issue by amedranogil** [universAAL/context#5]
even when CHe query is not found or fails.

**Comment by Alfiva** [comment]
Some explanation about the fix: Some of the internal calls of ProfServer Callee to CHE had to return a value, so it was not possible to simply relay the ServiceResponse from CHE (without modifying a lot the code). The solution here is throwing exceptions internally, but that also means whoever called the ProfServer will not get the relayed reason for CHE failing. Instead, a specificServiceError is returned from ProfServer, with the output of the reason explaining why it failed.
...Also: sorry for the mess in the commit but the changes required reformatting the code, thus the huge amount of lines modified - despite being a small fix
